### PR TITLE
Replace Node 0.12 with Node 7 and remove Node 0.10

### PR DESCRIPTION
**Pull request by svozza**

### CODE REVIEW

**Comment by davidchambers** [comment]
This appears not to have triggered CircleCI. Strange.

**Comment by svozza** [comment]
Hmmm, that is very odd. I mean of all things that should trigger a build, surely editting `.circle.yml` would be it!

**Comment by Shard** [comment]
Building forked requests was switched off, I switched it on.

**Comment by svozza** [comment]
Thanks @Shard . :)

**Comment by davidchambers** [comment]
:deciduous_tree:

**Pull request merged**
